# Generated by Django 4.1 on 2024-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_portfoliomanagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchaseorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalQuantity", models.BigIntegerField(default=0)),
                ("product", models.CharField(max_length=50)),
                ("orderDate", models.DateField(max_length=20)),
                ("totalCost", models.BigIntegerField(default=0)),
                ("pid", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "sos_purchaseorder",
            },
        ),
    ]
